### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier'

### ISSUE THREAD

**Issue by kine90** [GuidoBartoli/sherloq#65]
Error using python3.9
```
(sherloq) ┌──(kine㉿NOONE)-[/media/…/DATA/GitHub/sherloq/gui]
└─$ python sherloq.py
Traceback (most recent call last):
  File "/media/kine/DATA/GitHub/sherloq/gui/sherloq.py", line 20, in <module>
    from histogram import HistWidget
  File "/media/kine/DATA/GitHub/sherloq/gui/histogram.py", line 17, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.10/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py", line 12, in <module>
    from .backend_qt import QtCore, QtGui, _BackendQT, FigureCanvasQT
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 72, in <module>
    _MODIFIER_KEYS = [
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 73, in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier'

```
Error using python3.8

```
(sherloq) ┌──(kine㉿NOONE)-[/media/…/DATA/GitHub/sherloq/gui]
└─$ python sherloq.py              
Traceback (most recent call last):
  File "sherloq.py", line 20, in <module>
    from histogram import HistWidget
  File "/media/kine/DATA/GitHub/sherloq/gui/histogram.py", line 17, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qtagg.py", line 12, in <module>
    from .backend_qt import QtCore, QtGui, _BackendQT, FigureCanvasQT
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 72, in <module>
    _MODIFIER_KEYS = [
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 73, in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'KeyboardModifier'

```
PS: Why don´t you upload an environment.yaml file so people can install without having ti guess dependencies?
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment

**Comment by GuidoBartoli** [comment]
Some more info is needed:
- What is your operating system and platform?
- What operation did you try before receiving that error?

PS: I included a standard `requirements.txt` file to be used with `pip` to install all the required packages as explained in the [Installation](https://github.com/GuidoBartoli/sherloq#installation)

**Comment by GuidoBartoli** [comment]
Doing some research, I can guess it is related to this [pyside6 bug](https://stackoverflow.com/questions/74112099/importing-matplotlib-causes-int-argument-must-be-a-string-error), so if you already created the virtual environment maybe just upgrading that package to the latest version should fix this (I already committed in 4332fd9c3fd8fa3a229e3403997b566e0e6ff917 an updated `requirements.txt` that install the latest `pyside6` version).

**Comment by kine90** [comment]
Thanks for the advice! I have removed and reinstalled the last pyside6. Output from pip list:
```
PySide6                        6.4.1
PySide6-Addons                 6.4.1
PySide6-Essentials             6.4.1
```
Unfortunately the error is still here:
```
└─$ python sherloq.py
Traceback (most recent call last):
  File "sherloq.py", line 20, in <module>
    from histogram import HistWidget
  File "/media/kine/DATA/GitHub/sherloq/gui/histogram.py", line 17, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvas
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qtagg.py", line 12, in <module>
    from .backend_qt import QtCore, QtGui, _BackendQT, FigureCanvasQT
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 72, in <module>
    _MODIFIER_KEYS = [
  File "/home/kine/anaconda3/envs/sherloq/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 73, in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'KeyboardModifier'
```

**Comment by d1v1s38z3r0** [comment]
same issue here on linux Parrot 5.10 with virtualenv
pyside6 installed 641

**Comment by GuidoBartoli** [comment]
I have verified that it is a bug related to version 6.4+ of `pyside6`, so while I will look for a way to get it working with these newer versions, for the time being I have reverted the required version back to 6.3.2, so now it should work without any problems (thanks @kine90).

However, this is the output of `pip list` from inside the virtual environment:
```
Package                        Version
------------------------------ ----------
absl-py                        1.3.0
astor                          0.8.1
astunparse                     1.6.3
cachetools                     5.2.0
certifi                        2022.12.7
charset-normalizer             2.1.1
concurrent-iterator            0.2.6
contourpy                      1.0.6
cycler                         0.11.0
decorator                      5.1.1
flatbuffers                    22.12.6
fonttools                      4.38.0
gast                           0.4.0
google-auth                    2.15.0
google-auth-oauthlib           0.4.6
google-pasta                   0.2.0
grpcio                         1.51.1
h5py                           3.7.0
idna                           3.4
imageio                        2.23.0
joblib                         1.2.0
keras                          2.10.0
Keras-Applications             1.0.8
Keras-Preprocessing            1.1.2
kiwisolver                     1.4.4
libclang                       14.0.6
lxml                           4.9.1
Markdown                       3.4.1
MarkupSafe                     2.1.1
matplotlib                     3.6.0
networkx                       2.8.8
numpy                          1.24.0
oauthlib                       3.2.2
opencv-contrib-python-headless 4.6.0.66
opt-einsum                     3.3.0
packaging                      22.0
pandas                         1.5.0
Pillow                         9.3.0
pip                            22.3.1
protobuf                       3.19.6
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pyparsing                      3.0.9
PySide6                        6.3.2
PySide6-Addons                 6.3.2
PySide6-Essentials             6.3.2
python-dateutil                2.8.2
python-magic                   0.4.27
pytz                           2022.7
PyWavelets                     1.4.1
rawpy                          0.17.2
requests                       2.28.1
requests-oauthlib              1.3.1
rsa                            4.9
scikit-image                   0.19.3
scikit-learn                   1.1.2
scipy                          1.9.3
setuptools                     65.6.3
sewar                          0.4.5
shiboken6                      6.3.2
six                            1.16.0
tensorboard                    2.10.1
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
tensorflow                     2.10.1
tensorflow-estimator           2.10.0
tensorflow-io-gcs-filesystem   0.29.0
termcolor                      2.1.1
threadpoolctl                  3.1.0
tifffile                       2022.10.10
typing_extensions              4.4.0
urllib3                        1.26.13
Werkzeug                       2.2.2
wheel                          0.38.4
wrapt                          1.14.1
xgboost                        1.6.2
```

**Comment by GuidoBartoli** [comment]
> I would recommend uploading an environment.yaml file for conda users. Conda ensures much more accurate dependencies fulfillment than pip.

I agree with that, but at the moment conda does not support PySide6, so the GUI would not work in that environment.
